meta:
    author: Oğuzcan Demircan
    owner: Oğuzcan Demircan
    generator: Oğuzcan Demircan
    # docker, sql ve nosql veri tabanları, performans optimizasyonu, ci/cd ve verimlilik artıran geliştirici araçları ile ilgili yazılar.
    # My thoughts about Programming, Coffee, Bags and various other stuff
    # Programlama, Kahve, Çanta ve diğer çeşitli şeyler hakkındaki düşüncelerim
    description: "Laravel, php, vuejs, "
    keywords: "oguzcandemircan, oğuzcan demircan, laravel, developer, backend, php, yazılım, açık kaynak, software developer, open source, vue js, javascript"

default_language: tr

permalink: :title

navs:
-
  name: home
  url: /
-
  name: posts
  url: /posts
# - 
#     name: about
#     url: /about
# -
#     name: contact
#     url: /contact

social-network-links:
    twitter: oguzcandemircan
    github: oguzcandemircan
    gitlab: oguzcandemircan
    medium: oguzcandemircan
    linkedin: oguzcandemircan
    email: "demircanoguzcan@gmail.com"