meta:
    title: Oğuzcan Demircan
    author: Oğuzcan Demircan
    owner: Oğuzcan Demircan
    generator: Oğuzcan Demircan
    description: laravel, php, vuejs, javascript etc. my thinking about programming languages, frameworks, technologies, and various other things.
    description: laravel, php, vuejs, javascript vb. programlama dilleri, frameworkleri, teknolojileri ve diğer çeşitli şeyler hakkındaki düşüncelerim.
    keywords: oguzcandemircan, oğuzcan demircan, laravel, developer, backend, php, yazılım, açık kaynak, software developer, open source, vue js, javascript, yazılım geliştirici, geliştirici

default_language: tr

permalink: :title

navs:
-
  name: home
  url: /
-
  name: posts
  url: /posts
# - 
#     name: about
#     url: /about
# -
#     name: contact
#     url: /contact

social-network-links:
    twitter: oguzcandemircan
    github: oguzcandemircan
    gitlab: oguzcandemircan
    medium: oguzcandemircan
    linkedin: oguzcandemircan
    email: "demircanoguzcan@gmail.com"